defaults: &defaults
  adapter: postgresql
  encoding: utf8

development:
  database: jeffs_development
  <<: *defaults

test:
  database: jeffs_test
  <<: *defaults

production:
  database: jeffs
  <<: *defaults
